### ISSUE TITLE
$fml links broken

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#107]
Sometimes because of FML's terrible href set up (or least that's what UclCommander claims) it doesn't return a url but returns something like this

[ #17148663 | Today, an argument broke out between me, my girlfriend, and her sister. They were trying to convince me that not only were fairies real, but there were "scientific facts" that "prove" their existence. My girlfriend's 20 and her sister teaches primary school. FML | +33079/-4424 - /miscellaneous/17148663 ]

**Comment by UclCommander** [comment]
Fixed in the API endpoint.
