### ISSUE TITLE
[Fun] Support for OpenRCT API build info

### ISSUE THREAD

**Issue by matthijs186** [UclCommander/Dan#16]
Just a funny idea, but if we're gonna play it, this could be useful information since everyone's still on IRC anyway. :3

**EDIT:** Perhaps I could get myself into this as a plugin. I'll have a look at it.

https://openrct2.com/download
https://openrct2.com/api/get-latest-build

**Comment by matthijs186** [comment]
They have and are still updating their website, can't find documentation to API anymore so this idea will be on hiatus.

**Comment by FM1337** [comment]
Yeah they don't seem inclined to add apis any time soon :(

**Comment by matthijs186** [comment]
They probably abandoned their API since the whole project can be tracked on GitHub. Since it's possible to use the GitHub addon, I abandon this idea.
