### ISSUE TITLE
Command porting

### ISSUE THREAD

**Issue by UclCommander** [UclCommander/Dan#25]
Commands from v5 to be ported: 
- [x] 8ball (8b)
- [x] admins (owner)
- [x] booty
- [x] chaninfo (cinfo)
- [x] clones (like)
- [x] config
- [x] connect
- [x] cyanide (ch)
- [x] deop
- [x] devoice
- [x] disconnect
- [x] dongers
- [x] fmylife (fml)
- [x] geoip
- [x] hash
- [x] ignore
- [x] info
- [x] lenny
- [x] lmgtfy (lazy)
- [x] morepopcorn (moretrp, mp)
- [x] msg (say)
- [x] nbc
- [x] op
- [x] popcorn (trp)
- [x] quit
- [x] raw
- [x] restart (reboot)
- [x] roll
- [x] roulette (rr)
- [x] rpsls (rock, paper, scissors, lizard, spock)
- [x] stats
- [x] update
- [x] urban
- [x] version (v)
- [x] voice
- [x] whoopass

Suggestions are welcome. Feel free to post the command and what it would do, and if you can do it yourself, feel free to open a PR!

**Comment by FM1337** [comment]
Add cards against humanity game hosting mode pls.
