### ISSUE TITLE
[Needs Confirmation/Fix] If hooksPath doesn't exist add addonsPath?

### ISSUE THREAD

**Issue by matthijs186** [UclCommander/Dan#26]
**Branch: dan6.0**

So I was trying to discover if the array_random function from 5.1 was somewhere in 6.0, when in _functions.php_ I found the following:

> Line 125 - 138

``` php
if (!function_exists('hooksPath')) {

    /**
     * Gets the config path.
     *
     * @param string $path
     *
     * @return mixed
     */
    function addonsPath($path = '')
    {
        return dan()->make('path.addons').($path ? '/'.$path : null);
    }
}
```

I'm not sure if this is done on purpose or `hooksPath` needs to be changed.
Putting this here so I won't possibly forget to tell you later.

**Comment by UclCommander** [comment]
I must of missed that while doing some refactoring. Fixed via https://github.com/UclCommander/Dan/commit/ae71348e194e6765407942328e2b7352b6b1bf96
