### ISSUE TITLE
Add new features to Dan

### ISSUE THREAD

**Issue by FabTheZen** [UclCommander/Dan#4]
- Some features that would be nice: 8ball, wolfram alpha integration, weather, recipes, github, dice roll, countdown, dictionary definiton, TLD information, hug, url shortener.
- Add website resolution templates: (improve youtube), wikipedia, twitter, facebook, minecraftwiki.net
- help system that lists plugins available to the user requesting help.

**Comment by matthijs186** [comment]
Like it

**Comment by matthijs186** [comment]
Another idea: Add command prefix from config to the help lines when requesting help from a command

```
-Dan- hash <algo> <text> - Hashes <text> with <algo>
-Dan- !hash <algo> <text> - Hashes <text> with <algo>
```

**Comment by UclCommander** [comment]
- 8ball - planned
- dice roll - planned
- url shortener - planned
- TLD information - planned
- hug - in consideration
- wolfram alpha - in consideration
- weather - in consideration
- recipes - in consideration
- countdown - Unfortunately can't do, unless I add pThreads to the requirements

(of course, you can always make your own and open a PR to add it)

I do plan on adding more website-specific searches and title resolutions, specifically for twitter and github. I'll look into adding the others, but they may come at a later date.

@matthijs186 I have two possible ways to go about that. I can assume and automatically prepend the command prefix to every help line that gets sent back, or I can do a search replace for something like `{p}`.

**Comment by matthijs186** [comment]
IMO, the search replace identifier could be nice if it could/would be used in more places than only the help lines.
But yeah, it's an idea. Up to you.

**Comment by UclCommander** [comment]
Commands 8ball and dice roll has been added in 4.0.14-dev, as well as help prefixing using `{cp}`.
