### ISSUE TITLE
Idea: Warning System

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#50]
# The Warning System

<p>What this system will do is use the stats that Dan gets from doing $memory and monitor it so that if the memory usage gets to a unusual amount, it will send a warning via IRC and optionally PushBullet as well.</p>

<p>You could also have it watch the CPU usage of the server it's hosted on so that if it happens to be using a high amount of CPU, it would also send a warning out.</p>

# Examples of how the warning could look in IRC (note the text after Dan's name is in red)

<p>Dan <b>Warning my memory usage is currently above normal amounts, perhaps I should be rebooted to help fix this problem! I am currently using [Memory Usage of Dan here]</b></p>

<p>Dan <b>Warning my CPU usage is currently above normal amounts, perhaps I should be rebooted to help fix this problem! I am currently using [CPU Usage of Dan here]</b></p>

# Examples of how the warning could look in PushBullet notifications

<p><b>Warning Dan's memory usage is currently above normal amounts! Dan is currently using [current ram usage of Dan here]</b></p>

<p><b>Warning my CPU usage is currently above normal amounts! Dan is currently using [current CPU of Dan usage here]</b></p>

**Comment by UclCommander** [comment]
I don't know of any way PHP can get the CPU usage of the script it's currently executing. As for memory, it doesn't ever really get ridiculous and I'm not too worried about it.
