### ISSUE TITLE
Idea: Add time to ban command

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#51]
# Adding a time limit for dan's ban command in IRC

What this will do is allow you to define an amount of time of which the user will be banned for, followed by dan saying when the user will be unbanned.
# Command Arguments

s = seconds
m = minutes
h = hours
d = days
w = weeks
M = months
y = years
# Example

$ban Chris 5y
Chris will be unbanned on [insert unban date here] [From the time this was posted it would approximately be April 10th 2021 at 4:57 PM]

$ban Chris
Chris has been banned permanently

**Comment by matthijs186** [comment]
I don't think the ban command ever existed in Dan 5. Might as well add it with this feature.

**Comment by UclCommander** [comment]
This will require a new Timer system I'm currently working on.

**Comment by UclCommander** [comment]
So I sort of scrapped the Timer system idea I had because it wasn't working like I wanted it to. In the commit https://github.com/UclCommander/Dan/commit/3b4882c474d61a2b47b1b065b204d0549e8b90cd I built the $mute functionality directly into the Channel class using a new `system.ping` event. Much of the same code for mute can be reused here, except it'll have to go by `nick!user@host` format instead of the users id.

**Comment by matthijs186** [comment]
I'll have a look at it, thanks.

**EDIT:** Mute and kick are implemented in Channel. Would it matter if I attempted to add it to Channel instead of creating a command, since it's sort of a global thing anyway?

**Comment by UclCommander** [comment]
It'll still need a command to do the do. But there needs to be a `ban` method in Channel, I'm thinking with a signature `ban( string/User $user, bool $kick = false, string $reason = 'Requested')`.

**Comment by matthijs186** [comment]
Sure. Suggested format for kickban? How would one like switches?
`ban -k user`

**Comment by UclCommander** [comment]
Kickban could be a separate command, it would make it easier for people to find than having a `-k` flag.

**Comment by matthijs186** [comment]
Ban won't kick by default. Working on it.

**Comment by UclCommander** [comment]
Closed via https://github.com/UclCommander/Dan/commit/c9e232d35ea6fa28b2ba87d080d8ce96daff1870
