### ISSUE TITLE
Make Dan's quote database exportable to an html or php or text file

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#58]
This would be added to your web panel, and could export it to a php or html or text file.

if it were php or html it would look like:
< p >Check markiplier's twitter< /p >
< p > just get these robotic appliances and hook $user onto the api< /p >

Or if text file separate each quote by linebreak
Check markiplier's twitter
 just get these robotic appliances and hook $user onto the api

You could also have it add a number to each quote so
1. Check markiplier's twitter
2. just get these robotic appliances and hook $user onto the api

Or maybe even the date the quotes were added into the database.

You could also have it order by first to last by date added or maybe last to first, or maybe allow the user to choose the sorting, so many possibilities!

**Comment by UclCommander** [comment]
..I'm failing to see how this would be handy, other than to reuse it in other bots.

**Comment by FM1337** [comment]
Poetic Readings?
[Maybe add a way to turn his gibberish into a poem?]

Exporting it to other bots like you said.

Maybe for reading for fun, or displaying on a webpage on dan stats?
