### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#61]
Notice: Trying to get property of non-object in /root/Dan/addons/commands/fun/compliment.php on line 27
[02:41:48] [ERROR] Exception was thrown.
[02:41:48] [ERROR] Call to a member function query() on string
[02:41:48] [ERROR] On line 30
[02:41:48] [ERROR] Of file /root/Dan/addons/commands/fun/compliment.php

Notice: Undefined index: channel in /root/Dan/src/Core/ExceptionServiceProvider.php on line 26
[02:41:48] [ERROR] Exception was thrown.
[02:41:48] [ERROR] Call to a member function message() on null
[02:41:48] [ERROR] On line 26
[02:41:48] [ERROR] Of file /root/Dan/src/Core/ExceptionServiceProvider.php

Notice: Undefined index: channel in /root/Dan/src/Core/ExceptionServiceProvider.php on line 26

Fatal error: Uncaught Error: Call to a member function message() on null in /root/Dan/src/Core/ExceptionServiceProvider.php:26
Stack trace:
#0 [internal function]: Dan\Core\ExceptionServiceProvider->Dan\Core{closure}(Object(Error))
#1 /root/Dan/vendor/illuminate/container/Container.php(507): call_user_func_array(Object(Closure), Array)
#2 /root/Dan/src/Events/Event.php(137): Illuminate\Container\Container->call(Object(Closure), Array)
#3 /root/Dan/src/Events/Handler.php(137): Dan\Events\Event->call(Array)
#4 /root/Dan/src/Console/Console.php(324): Dan\Events\Handler->fire('console.excepti...', Array)
#5 /root/Dan/src/Irc/Connection.php(255): Dan\Console\Console->exception(Object(Error))
#6 /root/Dan/src/Irc/Connection.php(206): Dan\Irc\Connection->handleLine(':Allen!Allen@fm...')
#7 /root/Dan/src/Connection/Handler.php(158): Dan\Irc\Connection->read(Resource id #202)
#8 /root/Dan/src/Core/Dan.php(110): Dan\Connection\Handler->readConnections()
#9 /root/Dan/src/Console/Commands/DanCommand.php(38): Dan\Core\Dan->run()
#10  in /root/Dan/src/Core/ExceptionServiceProvider.php on line 26

below are lines 18 to 34
command(['compliment'])
    ->helpText('Compliments someone.')
    ->handler(function(\Dan\Irc\Connection $connection, Channel $channel, User $user, $message) {
        $websites = array('http://toykeeper.net/programs/mad/compliments', 'http://www.chainofgood.co.uk/passiton', 'http://www.madsci.org/cgi-bin/cgiwrap/~lynn/jardin/SCG');
        $website = array_rand($websites,1);
        $classes = array("large", "medium", "small");
        $class = array_rand($classes,1);
        $compliment = Web::xpath($website);
        if ($website == "http://www.chainofgood.co.uk/passiton"){
        $compliment = trim($compliment->query('//_[@class="large"]')->item(0)->textContent);
        }
        if ($website == "http://www.madsci.org/cgi-bin/cgiwrap/~lynn/jardin/SCG"){
        $compliment = trim($compliment->query('//h2')->item(0)->textContent);
        }
        if ($website == "http://toykeeper.net/programs/mad/compliments"){
        $compliment = trim($compliment->query('//_[@class="blurb_title_1"]')->item(0)->textContent);
        }

**Comment by UclCommander** [comment]
Fixed via https://github.com/UclCommander/Dan/commit/bb0a77184e455a66f8c3e6483dcfb67fe9ae4869
