### ISSUE TITLE
Cyanide & Happiness random comic picker

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#7]
Add a command to Dan (command prefix will probably be $ch or $comic) that will fetch a random comic from http://explosm.net/comics/random/

**Comment by matthijs186** [comment]
Like Alem suggested (http://skycld.co/PHb9ueTkbx.png), possibly add support for multiple comics.
Perhaps something like `$comic <ch/xkcd>` or just `$comic` for a complete random pick?

**Comment by UclCommander** [comment]
$ch and $xkcd added. Both accept an optional ID parameter.
