### ISSUE TITLE
Fix ignore command.

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#71]
When attempting to unignore a user using $ignore -user it doesn't actually unignore them, even when doing $unignore -hostmaskhere it still doesn't work.

**Comment by FM1337** [comment]
Quick question: when was the last time this feature was working?

**Comment by UclCommander** [comment]
It does work.. given that the bot has database information for a user if you just provide the nick. Otherwise, you have to provide `nick!user@host`.

**Comment by FM1337** [comment]
<Allen> $ignore *
-Dan- This user is already ignored.
<Allen> $ignore -*
-Dan- This user is not ignored.

**Comment by UclCommander** [comment]
Actually fixed via https://github.com/UclCommander/Dan/commit/3b2a9f8480e589fee732ec3f1569157761a0f6bd
