### ISSUE TITLE
$lastfm

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#8]
Add feature to dan to fetch user's info from lastfm and make it the user in a local database so that when the same user triggers the command it loads up the username by default.

e.g 

Allen: $lastm Allenlydiard
Dan: Allen Lydiard is listening to :songname: by :artist: from :album: :link to profile or song:
Allen: $lastfm
Dan: Allen Lydiard is listening to :songname: by :artist: from :album: :link to profile or song:

**Comment by UclCommander** [comment]
Added!
