### ISSUE TITLE
Steam Game Roulette 

### ISSUE THREAD

**Issue by FM1337** [UclCommander/Dan#88]
$rsg (short for random steam game, you could also do $rs) will use the url http://store.steampowered.com/explore/random/ to fetch a random steam game and display some info about it in the IRC chat, along with a link to the game page!

**Comment by FM1337** [comment]
Ideas for the command:
1. Get link to store page for random game.
2. Get game price also check if it's on sale.
   For the second option I'm looking at multple ways of doing this.
   The first way is to fetch from page source

```
<meta itemprop="priceCurrency" content="[Currency Here]">
<meta itemprop="price" content="[price here]">
```

That's one way, you could also look for the tags

```
<div class="game_purchase_action_bg">
<div class="discount_block game_purchase_discount"> <div class="discount_pct">-[num]%</div><div class="discount_prices"><div class="discount_original_price">[currency]$ [price]</div><div class="discount_final_price">[currency]$ [price]</div></div></div>   
```

Now of course this is from the page source, I'm not sure if the steam api will allow you to fetch game price, but if I find anything I'll update this post
3. Fetch release date
`Release Date: <span class="date">21 Jun, 2016</span>
`
4. Fetch rating

```
<div class="summary column">
<span class="game_review_summary positive" itemprop="description">Positive</span>
<span class="responsive_hidden">
```

Don't forget recent ones as well

```
<div class="summary column">
<span class="game_review_summary positive">Very Positive</span>
<span class="responsive_hidden">

```
1. Get a (small?) portion of the game's description
   `<div id="game_area_description" class="game_area_description">`

All of this can be done by reading and fetching the page's source. If I find any better way of doing all of this I'll update this post.
(note [num] and [currency] are replaced with whatever is on the page)
(Please also note that some games do not have the recent reviews tag)

Optional:
6. Fetch tags

```
<div class="glance_tags popular_tags" data-appid="464780">
<a href="http://store.steampowered.com/tag/en/Free%20to%20Play/?snr=1_5_9__409" class="app_tag" style="display: none;">Free to Play</a>
<a href="http://store.steampowered.com/tag/en/Adventure/?snr=1_5_9__409" class="app_tag" style="display: none;">
Adventure</a>
<a href="http://store.steampowered.com/tag/en/Anime/?snr=1_5_9__409" class="app_tag" style="display: none;">Anime</a>
<a href="http://store.steampowered.com/tag/en/Visual%20Novel/?snr=1_5_9__409" class="app_tag" style="display: none;">Visual Novel</a>
<div class="app_tag add_button" onclick="ShowAppTagModal( 464780 )"+</div>
</div></div>

```

**Comment by FM1337** [comment]
[Possible bug in the future]
Age check might popup for some games, I'm not sure how we'd get past that.

**Comment by UclCommander** [comment]
Unfortunately I don't think we could get past that.. I could re-query a random game if we run into that, or send a "Game needs age check" message with a link.

**Comment by FM1337** [comment]
Did some digging, maybe this might help? 
http://stackoverflow.com/questions/22140197/how-to-pass-age-verification-with-dom

**Comment by UclCommander** [comment]
Magical. That looks like it could work.

**Comment by FM1337** [comment]
Ratings Colours
Overwhelmingly Positive: Bright Bold Green maybe bold lime
Very Positive: Bright or lime Green not bolded
Positive: Dark Green
Mostly Positive: Green
Mixed: Orange
Mostly Negative: Red
Negative: Dark Red
Very Negative: Darker Red? I dunno 
Overwhelmingly Negative: Bold Darkest Red

Maybe you can upgrade these colour choices with some colours you have in mind.

**Comment by UclCommander** [comment]
Added via https://github.com/UclCommander/Dan/commit/8afe10b7a010cbab19414e5f9f0d8cb781394656
