### ISSUE TITLE
Title crawling www urls

### ISSUE THREAD

**Issue by ghost** [UclCommander/Dan#91]
Add title crawling to messages such as www.google.com - exactly the same as http://google.com

**Comment by matthijs186** [comment]
So you mean URL detection without necessity of `http(s)://`, or replacing it with `www` specifically?

**Comment by ghost** [comment]
Already spoke to UclCommander, but URL detection without having to use http(s)://

**Comment by UclCommander** [comment]
I'd rather not do this. It could lead to some issues with false positive urls.
